### ISSUE TITLE
Failed to set up bot 😕 Check your input.

### ISSUE THREAD

**Issue by nathansmonk** [fplbot/fplbot#150]
I have tried to use this from www.fplbot.app and received the following message:

Failed to set up bot 😕 Check your input.

My league ID was discovered, and I tried the channel name with both the # and without.

**Comment by johnkors** [comment]
Thanks for letting us know! There was a bug, but should be good now. 

Fixed in 508814bfbce63117b0ee3f72c547d916d395e09f
