### ISSUE TITLE
Bug: Mentions not working

### ISSUE THREAD

**Issue by eoftedal** [fplbot/fplbot#239]
I'm not sure how the matching from FPL to slack works today, but we've seen occurences where the mentions are just "normal text" and they don't seem to reference a slack user. According to the post below, it seems it should use a userid in the API when mentioning a user: https://api.slack.com/changelog/2017-09-the-one-about-usernames

> The undocumented approach to mentioning users via the API — <@username> — will no longer function after September 12, 2018. Please reference with the user ID format (<@U123>) instead.

**Comment by johnkors** [comment]
Nice! We'll test that from GW2. Hope it works better 🤞

**Comment by eoftedal** [comment]
That was fast!
