### ISSUE TITLE
Use `webname` instead of full name in fixture events

### ISSUE THREAD

**Issue by johnkors** [fplbot/fplbot#293]
![image](https://user-images.githubusercontent.com/206726/144608842-825df1c8-16c7-4002-8856-8932a4251f56.png)

Assuming it's because of all these Portuguese names 😁

![image](https://user-images.githubusercontent.com/206726/144609080-67d86dfc-31cb-4b05-adf8-b33a3296254f.png)

Remember we discussed this wayyy back. Anyone against moving to `webname` ..?

**Comment by skjelbek** [comment]
Haha, I remember. We really should change, yes.
