### ISSUE TITLE
Goal Score Notifications Wrong

### ISSUE THREAD

**Issue by thomasjcf29** [fplbot/fplbot#317]
When an additional score comes in during a match the notification highlights information about the score, but the match score is incorrect.

This is for the discord bot.

For example:

1st Goal:
![Screenshot from 2022-08-07 18-40-14](https://user-images.githubusercontent.com/12817571/183303997-37774256-f0e8-4e43-85f6-171a4683a8e4.png)

2nd Goal:
![Screenshot from 2022-08-07 18-39-59](https://user-images.githubusercontent.com/12817571/183304000-544aad2f-9f6e-4928-8a6c-dfefc3f893f9.png)

Final Result:
![Screenshot from 2022-08-07 18-40-26](https://user-images.githubusercontent.com/12817571/183304007-bb75150b-02ca-4637-9fdf-27bffb6cdd8a.png)

Many Thanks,
Tom Franklin.

**Comment by johnkors** [comment]
Thanks. Noticed this last season as well. Looks like the FPL APIs are bit slower updating the match score than the goal scorers. Will check if we can get around it somehow.

**Comment by johnkors** [comment]
Fixed in #329
