### ISSUE TITLE
Bug: Unable to follow league in Slack

### ISSUE THREAD

**Issue by johnkors** [fplbot/fplbot#320]
![image](https://user-images.githubusercontent.com/206726/184529539-fb3b004a-3f4d-4b3c-a341-f06c945af8ac.jpeg)

**Comment by larsjaakko** [comment]
@johnkors Having this issue currently — any workarounds?

**Comment by johnkors** [comment]
Some clients auto-format, so maybe you're using the slack mobile app here? 

Remove the phone number auto-formatting ("remove link") or use a client that does not auto format numbers starting with 18. I don't get the issue on the desktop client at least.

<img src="https://github.com/user-attachments/assets/49dda484-d259-44ac-ae58-0cb9cab6e8d3" width=300 />

**Comment by larsjaakko** [comment]
That was it! Thanks for the quick reply.
